version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sofomo-assigment-backend
    container_name: sofomo-assigment-backend
    command: yarn dev
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - sofomo-assigment-network
  mongo:
    image: mongo
    container_name: sofomo-assigment-database
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - sofomo-assigment-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sofomo-assigment-frontend
    container_name: sofomo-assigment-frontend
    command: yarn start
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - sofomo-assigment-network
    environment:
      CHOKIDAR_USEPOLLING: "true"
networks:
    sofomo-assigment-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local