version: '3.7'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sofomo-assigment-backend
    container_name: sofomo-assigment-backend
    command: yarn dev
    volumes:
      - './:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      - sofomo-assigment-network
  mongo:
    image: mongo
    container_name: sofomo-assigment-database
    volumes:
      - 'data-volume:/data/db'
    ports:
      - '27017:27017'
    networks:
      - sofomo-assigment-network
networks:
  sofomo-assigment-network:
    driver: bridge
volumes:
  data-volume: null
  node_modules: null
  web-root:
    driver: local
